# DV01 and Position Sizing
dv01:
  target: 100  # Target DV01 per trade in dollars
  ratios:
    # Use dynamic calculation for 2s10s (null or omit to compute on the fly)
    2s10s: null
    # Keep static ratio for 5s30s
    5s30s: null

# Transaction Costs
transaction_costs:
  spread_bp: 0.5  # Cost in basis points per leg
  dv01_cost: 0.1  # Cost in dollars per DV01 traded

# Signal Thresholds
signal_thresholds:
  next_day:
    min_change_bp: 0.75  # Minimum predicted change in basis points
    neutral_zone: [-0.3, 0.3]  # Range considered neutral
  direction:
    probability: 0.65  # Minimum probability for binary classification
  ternary:
    probability: 0.65  # Minimum probability for ternary classification
  ensemble:
    min_agreement: 2  # Minimum number of models that must agree

# Position Management
position:
  rebalancing:
    frequency: "daily"  # Options: daily, weekly
    threshold_pct: 0.05  # Rebalance if DV01 neutrality deviates by this percentage
  max_position:
    dv01_per_spread: 500  # Maximum DV01 exposure per spread
    total_portfolio: 1000  # Maximum total portfolio DV01

# Risk Management
risk:
  max_drawdown: 0.10  # Maximum allowed drawdown
  var_confidence: 0.95  # VaR confidence level
  position_limits:
    max_concentration: 0.5  # Maximum allocation to single spread
    correlation_threshold: 0.7  # Maximum allowed correlation between spreads

# Model Ensemble
ensemble:
  weights:
    next_day: 0.35
    direction: 0.35
    ternary: 0.30
  confidence_scaling: true  # Whether to scale signals by model confidence
  neutral_threshold: 0.4  # New parameter: minimum vote required for directional signal

# Portfolio Construction
portfolio:
  weighting_scheme: "risk_adjusted"  # Options: equal_dv01, risk_adjusted
  rebalancing_frequency: "weekly"
  vol_target: 0.10  # Annual volatility target
  lookback_window: 252  # Days for calculating risk metrics

# Paths
paths:
  data: "data/processed/"
  model_pickles: "results/model_pickles/"
  results: "results/"
  logs: "results/logs/"
  signals: "results/signals/"
  backtest: "results/backtest/" 